proxy-providers:
  ALL:
    type: http
    url: "https://raw.githubusercontent.com/MaxLansquenet/Clash/refs/heads/master/Clash-ConfigOld.yaml" # è®¢é˜…é“¾æ¥
    path: "./ALL.yaml" # é…ç½®æ–‡ä»¶ç¼“å­˜çš„ä½ç½®
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
    proxy: ğŸ¯ GitHub
      
mixed-port: 8086
allow-lan: true
mode: Rule
log-level: warning
external-controller: 0.0.0.0:9097   

proxy-groups:
  - name: Å  Steam
    type: select
    include-all: true
    exclude-filter: "CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    url: https://store.steampowered.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - DIRECT

  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    include-all: true
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:

  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    include-all: true
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:
    
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    include-all: true
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
 
  - name: ğŸ¯ GitHub
    type: select
    url: https://www.github.com/generate_204
    interval: 300
    tolerance: 50
    include-all: true
    exclude-filter: "CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|æœªçŸ¥|æœºåœº|cn"
    strategy: consistent-hashing   #round-robin
    proxies:

  - name: ğŸ¥ å¥ˆé£è§†é¢‘
    type: load-balance
    url: https://www.netflix.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    strategy: consistent-hashing   #round-robin
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:

  - name: ğŸ“¹ æ²¹ç®¡è§†é¢‘
    type: select
    url: https://www.youtube.com/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    strategy: consistent-hashing   #round-robin
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:

  - name: ğŸ¥ Tiktok
    type: select
    url: https://www.tiktok.com
    include-all: true
    interval: 300
    tolerance: 50
    strategy: consistent-hashing   #round-robin
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:
        - ğŸ¥ Tiktok_all
    
  - name: ğŸ¥ Tiktok_all
    type: load-balance
    url: https://www.tiktok.com
    include-all: true
    interval: 300
    tolerance: 50
    strategy: consistent-hashing   #round-robin
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:
    
  - name: ğŸ’¬ OpenAi
    type: load-balance
    url: https://www.chatgpt.com
    include-all: true
    interval: 300
    tolerance: 50
    strategy: consistent-hashing   #round-robin
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:


  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
    type: load-balance
    url: https://www.telegram.org/generate_204
    include-all: true
    interval: 300
    tolerance: 50
    strategy: consistent-hashing   #round-robin
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:

  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: load-balance
    url: http://www.msftncsi.com/ncsi.txt
    include-all: true
    interval: 300
    tolerance: 50
    strategy: consistent-hashing   #round-robin
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:

  - name: ğŸ è‹¹æœæœåŠ¡
    type: load-balance
    url: http://captive.apple.com
    include-all: true
    interval: 300
    tolerance: 50
    strategy: consistent-hashing   #round-robin
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:

  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    url: http://www.google.com/blank.html
    include-all: true
    strategy: consistent-hashing   #round-robin
    interval: 300
    tolerance: 50
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:

  - name: âœ Mozilla
    type: load-balance
    url: http://detectportal.firefox.com/success.txt
    include-all: true
    strategy: consistent-hashing   #round-robin
    interval: 300
    tolerance: 50
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:
    
  - name: APK_Apkpure
    type: load-balance
    url: http://apkpure.com/
    include-all: true
    strategy: consistent-hashing   #round-robin
    interval: 300
    tolerance: 50
    exclude-filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|ä¸­åœ‹|cn|æœªçŸ¥"
    proxies:

  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸŸ æ¼ç½‘ä¹‹é±¼
      - DIRECT

  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - ğŸ¯ å…¨çƒç›´è¿

  - name: ğŸƒ åº”ç”¨å‡€åŒ–
    type: select
    proxies:
      - REJECT
      - ğŸ¯ å…¨çƒç›´è¿

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ä¸€èˆ¬ä¸ç”¨
      - DIRECT

  - name: ä¸€èˆ¬ä¸ç”¨
    type: select
    include-all: true
    filter: "HK|é¦™æ¸¯|hk|hongkong|hong kong|CN|ä¸­å›½|æ¸—é€|cn|æœªçŸ¥"
    proxies:

rule-providers:

  AWAvenue:
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml
    path: ./ruleset/AWAvenue-Ads-Rule-Clash-Classical.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http

  Steams:
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    path: ./ruleset/Steam.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http
    
  Microsoft:
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http

  Apkpure:
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apkpure/Apkpure.yaml
    path: ./ruleset/Apkpure.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http

  Mozillas:
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Mozilla/Mozilla.yaml
    path: ./ruleset/Mozilla.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http

  IPTV_Mainland:
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/IPTVMainland/IPTVMainland_Classical.yaml
    path: ./ruleset/IPTV_Mainland.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http
    
  Advertising:
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml
    path: ./ruleset/Advertising.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http

  GitHub:
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
    path: ./ruleset/GitHub.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http
    
  Netflix:
    url: https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
    path: ./ruleset/Netflix.list
    behavior: classical
    interval: 86400
    format: text
    type: http

  YouTube:
    url: https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
    behavior: classical
    interval: 86400
    format: text
    type: http

  Tiktok:
    url: https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs
    path: ./ruleset/tiktok.mrs
    behavior: domain
    interval: 86400
    format: mrs
    type: http

  OpenAi:
    url: https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
    behavior: classical
    interval: 86400
    format: text
    type: http
    
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  directto:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  AppleTV:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml"
    path: ./ruleset/AppleTV.yaml
    interval: 86400
rules:  
    
  - RULE-SET,reject,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,Advertising,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,AWAvenue,ğŸ›‘ å…¨çƒæ‹¦æˆª  

  - RULE-SET,icloud,ğŸ è‹¹æœæœåŠ¡,no-resolve
  - RULE-SET,AppleTV,ğŸ è‹¹æœæœåŠ¡,no-resolve
  - RULE-SET,apple,ğŸ è‹¹æœæœåŠ¡,no-resolve
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡,no-resolve
  - DOMAIN-SUFFIX,microsoft.com,â“‚ï¸ å¾®è½¯æœåŠ¡,no-resolve
  - RULE-SET,GitHub,ğŸ¯ GitHub,no-resolve
  - DOMAIN-SUFFIX,github.com,ğŸ¯ GitHub,no-resolve
  - RULE-SET,Netflix,ğŸ¥ å¥ˆé£è§†é¢‘,no-resolve
  - RULE-SET,YouTube,ğŸ“¹ æ²¹ç®¡è§†é¢‘,no-resolve
  - RULE-SET,Tiktok,ğŸ¥ Tiktok,no-resolve
  - RULE-SET,telegramcidr,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
  - RULE-SET,OpenAi,ğŸ’¬ OpenAi,no-resolve 
  - RULE-SET,google,ğŸ“¢ è°·æ­ŒFCM,no-resolve
  - DOMAIN-SUFFIX,google.com,ğŸ“¢ è°·æ­ŒFCM,no-resolve
  - DOMAIN-SUFFIX,googleapis.com,ğŸ“¢ è°·æ­ŒFCM,no-resolve
  - DOMAIN-SUFFIX,uptodown.com,ğŸ“¢ è°·æ­ŒFCM,no-resolve
  - RULE-SET,Mozillas, âœ Mozilla,no-resolve
  - RULE-SET,Steams, Å  Steam,no-resolve
  - RULE-SET,Apkpure, APK_Apkpure,no-resolve

  - DOMAIN-SUFFIX,top81cn.cn,ğŸŸ æ¼ç½‘ä¹‹é±¼

  - GEOIP,CN,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT  
  - RULE-SET,applications,DIRECT
  - DOMAIN,board.zash.run.place,DIRECT
  - DOMAIN,metacubex.github.io,DIRECT
  - RULE-SET,directto,DIRECT   
  - RULE-SET,private,DIRECT   
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,IPTV_Mainland,DIRECT



  - MATCH,ğŸ¯ å…¨çƒç›´è¿
